branch-defaults:
  develop:
    environment: gp-dev-api
  qa:
    environment: gp-api-qa
  master:
    environment: gp-api-prod
environment-defaults:
  tgp-api-dev:
    branch: null
    repository: null
global:
  application_name: goodparty.org
  default_ec2_keyname: thegoodparty
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-tgp
  sc: git
  workspace_type: Application
