module.exports = {
  inputs: {
    slug: {
      type: 'string',
      required: true,
    },
  },

  exits: {
    success: {
      description: 'ok',
      responseType: 'ok',
    },
    badRequest: {
      description: 'badRequest',
      responseType: 'badRequest',
    },
  },
  fn: async function (inputs, exits) {
    try {
      const { slug } = inputs;
      const campaign = await Campaign.findOne({ slug }).populate(
        'pathToVictory',
      );
      const { data, details, pathToVictory } = campaign;

      if (
        !pathToVictory?.data?.electionType ||
        !pathToVictory?.data?.electionLocation ||
        data.hasVoterFile
      ) {
        console.log('Path to Victory is not set.', campaign);
        return exits.badRequest({ message: 'Path to Victory is not set.' });
      }
      await Campaign.updateOne({ id: campaign.id }).set({
        data: { ...campaign.data, hasVoterFile: 'processing' },
      });
      let independentStateParties = getIndependentStateParties(details.state);
      const filters = {
        Parties_Description: independentStateParties,
      };

      await sails.helpers.campaign.voterDataHelper(
        campaign.id,
        details.state,
        pathToVictory.data.electionType,
        pathToVictory.data.electionLocation,
        filters,
        false,
      );

      return exits.success({
        message: 'ok',
      });
    } catch (e) {
      console.log(e);
      await sails.helpers.slack.errorLoggerHelper(
        'Error purchasing voter file.',
        e,
      );
      return exits.badRequest({ message: 'Error purchasing voter file.' });
    }
  },
};

function getIndependentStateParties(state) {
  // this list was generated from sails.helpers.campaign.getParties();
  let allParties = {
    AL: ['Non-Partisan'],
    AK: [
      'Constitution',
      'Non-Partisan',
      'Other',
      'Green Libertarian',
      'Independence',
      'Libertarian',
    ],
    AZ: [
      'Conservative',
      'American',
      'Non-Partisan',
      'Green',
      'Other',
      'Liberal',
      'Registered Independent',
      'Moderate',
      'Natural Law',
      'Libertarian',
      'Tea',
    ],
    AR: ['Non-Partisan', 'Green', 'Reform', 'Libertarian'],
    CA: [
      'American Independent',
      'Non-Partisan',
      'Green',
      'Other',
      'Peace and Freedom',
      'Natural Law',
      'Libertarian',
      'Reform',
    ],
    CO: ['Constitution', 'Non-Partisan', 'Green', 'Other', 'Libertarian'],
    CT: [
      'Non-Partisan',
      'Green',
      'Other',
      'Registered Independent',
      'Libertarian',
      'Working Family Party',
    ],
    DE: [
      'No Labels',
      'Conservative',
      'American',
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Other',
      'Liberal',
      'Registered Independent',
      'Natural Law',
      'Libertarian',
      'Working Family Party',
      'Reform',
      'Socialist Labor',
    ],
    DC: ['Non-Partisan', 'Green', 'Other', 'Libertarian'],
    FL: [
      'Conservative',
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Other',
      'Registered Independent',
      'Socialist',
      'Libertarian',
    ],
    GA: ['Non-Partisan'],
    HI: ['Non-Partisan'],
    ID: ['Constitution', 'Non-Partisan', 'Libertarian'],
    IL: [
      'Citizens Republican',
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Harold Washington Democrat',
      'Registered Independent',
      'Moderate',
      'Citizens',
      'Harold Washington Republican',
      'Harold Washington',
      'Reform',
      'Libertarian',
      'Prohibition',
    ],
    IN: ['Non-Partisan', 'Other'],
    IA: ['Non-Partisan', 'Green', 'Libertarian'],
    KS: ['Non-Partisan', 'Libertarian'],
    KY: [
      'Constitution',
      'Green',
      'Other',
      'Registered Independent',
      'Libertarian',
      'Reform',
      'Socialist Labor',
    ],
    LA: ['Non-Partisan', 'Green', 'Libertarian'],
    ME: ['Non-Partisan', 'Green', 'Other', 'Libertarian'],
    MD: [
      'Conservative',
      'Communist',
      'Bull Moose',
      'American Independent',
      'Alliance',
      'Constitution',
      'Bread and Roses',
      'American',
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Anarchist',
      'Other',
      'Liberal',
      'Christian',
      'Registered Independent',
      'Peace and Freedom',
      'Peoples',
      'Populist',
      'Right to Life',
      'Natural Law',
      'Social Democrat',
      'Natural Party',
      'Socialist',
      'Libertarian',
      "Worker's Party",
      'Individualist',
      'Reform',
      'Whig',
      'Taxpayers',
      'Patriot',
      'Tax',
    ],
    MA: [
      'Conservative',
      'American Independent',
      'Constitution',
      'Non-Partisan',
      'Green',
      'Other',
      'Natural Law',
      'Socialist',
      'Libertarian',
      'Rainbow',
      'Working Family Party',
      'Reform',
      'Prohibition',
    ],
    MI: ['Non-Partisan'],
    MN: ['Non-Partisan'],
    MS: ['Non-Partisan', 'Green', 'Other'],
    MO: ['Non-Partisan', 'Libertarian'],
    MT: ['Non-Partisan'],
    NE: ['Non-Partisan', 'Other', 'Libertarian'],
    NV: [
      'American Independent',
      'Non-Partisan',
      'Green',
      'Other',
      'Natural Law',
      'Libertarian',
    ],
    NH: ['Non-Partisan'],
    NJ: [
      'Conservative',
      'Constitution',
      'Non-Partisan',
      'Green',
      'Natural Law',
      'Socialist',
      'Libertarian',
      'Reform',
    ],
    NM: [
      'Conservative',
      'Communist',
      'American Independent',
      'Alliance',
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Other',
      'Liberal',
      'Registered Independent',
      'Peace and Freedom',
      'Socialist',
      'Libertarian',
      'Working Family Party',
      'Prohibition',
      'Socialist Labor',
      'Taxpayers',
    ],
    NY: [
      'Conservative',
      'Non-Partisan',
      'Green',
      'Other',
      'Independence',
      "Women's Equality Party",
      'Libertarian',
      'Working Family Party',
      'Reform',
    ],
    NC: ['No Labels', 'Non-Partisan', 'Green', 'Libertarian'],
    ND: ['Non-Partisan'],
    OH: [
      'Constitution',
      'Non-Partisan',
      'Green',
      'Natural Law',
      'Socialist',
      'Libertarian',
      'Reform',
    ],
    OK: ['Non-Partisan', 'Libertarian'],
    OR: [
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Other',
      'Registered Independent',
      'Progressive',
      'Libertarian',
      'Working Family Party',
    ],
    PA: [
      'Conservative',
      'Communist',
      'Bull Moose',
      'American Independent',
      'Constitution',
      'Free Choice',
      'American',
      'Non-Partisan',
      'Constitutional',
      'Freedom',
      'Green',
      'Consumer',
      'Anarchist',
      'Other',
      'Federalist',
      'Liberal',
      'Labor',
      'Christian',
      'Registered Independent',
      'Peace and Freedom',
      'Populist',
      'Right to Life',
      'Natural Law',
      'Independence',
      'Social Democrat',
      'Independent Republican',
      'Socialist',
      'Progressive',
      'Independent Democrat',
      'Libertarian',
      'Patriot',
      'Reform',
      'Socialist Labor',
      'Whig',
      'Prohibition',
      'Rainbow',
      'Taxpayers',
    ],
    RI: ['Non-Partisan'],
    SC: ['Non-Partisan'],
    SD: [
      'No Labels',
      'Conservative',
      'Communist',
      'Bull Moose',
      'Constitution',
      'American',
      'Non-Partisan',
      'Constitutional',
      'Green',
      'Other',
      'Federalist',
      'Liberal',
      'Registered Independent',
      'Moderate',
      'Socialist',
      'Progressive',
      'Libertarian',
      'Whig',
      'Tea',
      'Reform',
      'Individualist',
    ],
    TN: ['Non-Partisan'],
    TX: ['Non-Partisan'],
    UT: [
      'American Independent',
      'Constitution',
      'Non-Partisan',
      'Green',
      'Other',
      'Libertarian',
    ],
    VT: ['Non-Partisan'],
    VA: ['Non-Partisan'],
    WA: ['Non-Partisan'],
    WV: [
      'Constitution',
      'Non-Partisan',
      'Green',
      'Other',
      'Registered Independent',
      'Mountain',
      'Libertarian',
    ],
    WI: ['Non-Partisan'],
    WY: [
      'American Independent',
      'Constitution',
      'Non-Partisan',
      'Other',
      'Natural Law',
      'Libertarian',
    ],
  };
  let stateParties = allParties[state];
  return stateParties;
}
