name: Elastic Beanstalk Deployment

on:
  push:
    branches:
      - develop
      - qa
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install virtualenv
        run: python -m pip install virtualenv

      - name: Install EB CLI
        run: |
          curl -Lo /tmp/awsebcli.zip https://github.com/aws/aws-elastic-beanstalk-cli-setup/archive/master.zip
          unzip /tmp/awsebcli.zip -d /tmp/ebcli
          python /tmp/ebcli/aws-elastic-beanstalk-cli-setup-master/scripts/ebcli_installer.py
          echo "/home/runner/.ebcli-virtual-env/executables" >> $GITHUB_PATH

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[eb-cli-tgp]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = us-west-2" >> ~/.aws/config # change the region to whatever you need
          env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Determine Environment Name and Deploy
        run: |
          ENV_NAME=""
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            ENV_NAME="gp-dev-api"
          elif [ "${{ github.ref }}" == "refs/heads/qa" ]; then
            ENV_NAME="gp-qa-api"
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            ENV_NAME="gp-prod-api"
          fi

          if [ -z "$ENV_NAME" ]; then
            echo "No environment name set for this branch, skipping deployment."
            exit 0
          else
            eb use $ENV_NAME
            eb deploy
          fi

      - name: Notify Slack on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,took # Customize as per your needs
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,took # Customize as per your needs
          only_mention_if: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
